---
title: "Exercise: Explore, Clean, and Wrangle Data"
author: Kenji
format: html
---
## About the data

The data, "SBC LTER: Reef: Abundance, size and fishing effort for California Spiny Lobster (Panulirus interruptus), ongoing since 2012," can be found on the EDI Data Portal[^1].

## Setup

```{r}
#| include: false
library(tidyverse)

```

## Read and explore data

```{r}
# download data
f1 <- "Time-series of lobster abundance and size.csv"
if(!(f1 %in% list.files("data"))){
  download.file(
    url = "https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-sbc.77.8&entityid=f32823fba432f58f66c06b589b7efac6",
    destfile = file.path("data", f1)
  )
}

f2 <- "Time-series of lobster trap buoy counts .csv"
if(!(f2 %in% list.files("data"))){
  download.file(
    url = "https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-sbc.77.8&entityid=66dd61c75bda17c23a3bce458c56ed84",
    destfile = file.path("data", f2)
  )
}

# read data in
lobster_abundance <- read_csv(file.path("data", f1))

lobster_traps <- read_csv(file.path("data", f2))
```
### Explore

```{r}
glimpse(lobster_abundance)
```

```{r}
glimpse(lobster_traps)
```


## Exercise 1 
## Exercise 2
## Exercise 3
## Exercise 4 
## Exercise 5
## Exercise 6

## References
[^1]: Santa Barbara Coastal LTER, D. Reed, and R. Miller. 2022. SBC LTER: Reef: Abundance, size and fishing effort for California Spiny Lobster (Panulirus interruptus), ongoing since 2012 ver 8. Environmental Data Initiative. https://doi.org/10.6073/pasta/25aa371650a671bafad64dd25a39ee18 (Accessed 2023-06-29).